apiVersion: missioncontrol.datastax.com/v1beta2
kind: MissionControlCluster
metadata:
  name: ${cluster_name}
  namespace: ${project_name}
spec:
  createIssuer: true
  dataApi:
    enabled: false
  encryption:
    internodeEncryption:
      certs:
        createCerts: true
      enabled: true
  k8ssandra:
    auth: true
    cassandra:
      config:
        cassandraYaml: {}
        dseYaml: {}
        jvmOptions:
          gc: G1GC
          heapSize: 1Gi
      datacenters:
%{ for dc in datacenters ~}
        - config:
            cassandraYaml: {}
            dseYaml: {}
          datacenterName: ${dc.datacenterName}
          dseWorkloads:
            graphEnabled: false
            searchEnabled: false
          k8sContext: ''
          metadata:
            name: ${project_name}-${dc.datacenterName}
            pods: {}
            services:
              additionalSeedService: {}
              allPodsService: {}
              dcService: {}
              nodePortService: {}
              seedService: {}
          networking: {}
          perNodeConfigMapRef: {}
          racks:
%{ for rack_num in range(dc.num_racks) ~}
            - name: "rack-${rack_num + 1}"
              nodeAffinityLabels: {}
%{ endfor ~}
          size: ${dc.num_racks * dc.nodes_per_rack}
          stopped: false
%{ endfor ~}
      resources:
        requests:
          cpu: 1000m
          memory: 4Gi
      serverImage: ''
      serverType: hcd
      serverVersion: 1.1.0
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: linode-block-storage-retain
      superuserSecretRef:
        name: ${cluster_name}-superuser